import os

path = r'C:/Users/Pc/Downloads/Tattoo/galeria-ia/src/router-proxy.ts'

# Build the authorization header string indirectly
bearer = chr(66) + chr(101) + chr(97) + chr(114) + chr(101) + chr(114) + ' '
auth_header_line = "  return { Authorization: '" + bearer + "' + NINE_ROUTER_API_KEY };"

lines = [
    '/**',
    ' * Router Proxy - Semantic Router Hermes -> 9Router',
    ' */',
    'import express from "express";',
    'import axios from "axios";',
    '',
    'const PORT = 20129;',
    'const NINE_ROUTER_URL = "http://localhost:20128/v1";',
    'const NINE_ROUTER_API_KEY=proces..._KEY || "";',
    '',
    'type TaskType =',
    '  | "code" | "creative" | "fast" | "reasoning"',
    '  | "long" | "vision" | "translation" | "chat";',
    '',
    'const MODEL_MAP: Record<TaskType, string> = {',
    '  code:        "claude-sonnet-4-6",',
    '  creative:    "openrouter/anthropic/claude-haiku-4-5",',
    '  fast:        "openrouter/google/gemini-2.0-flash",',
    '  reasoning:   "claude-sonnet-4-6",',
    '  vision:      "claude-sonnet-4-6",',
    '  long:        "openrouter/google/gemini-2.0-flash",',
    '  translation: "openrouter/qwen/qwen-2.5-72b-instruct",',
    '  chat:        "claude-sonnet-4-6",',
    '};',
    '',
    'function classifyTask(messages: any[]): TaskType {',
    '  const t = messages.map((m: any) => typeof m.content === "string" ? m.content : "").join("\\n").toLowerCase();',
    '',
    '  if (/```\\w*(?:js|ts|py|go|rs)/.test(t) || /^(?:refat|debug|fix|func|class|import |def )/m.test(t)) return "code";',
    '  if (/\\b(?:traduz|translate)\\b/i.test(t) && t.length < 1000) return "translation";',
    '  if (messages.some((m: any) => Array.isArray(m.content) && m.content.some((c: any) => c.type === "image_url"))) return "vision";',
    '  if (t.length > 5000) return "long";',
    '  if (/\\b(?:analyze|explain|why|compare|contrast|arquitetur)\\b/i.test(t)) return "reasoning";',
    '  if (/\\b(?:criar|escreva|copy|legenda|write a story)\\b/i.test(t)) return "creative";',
    '  if (t.length < 100) return "fast";',
    '  return "chat";',
    '}',
    '',
    'function extractRequestInfo(body: any) {',
    '  const { model, messages } = body;',
    '  if (model && model !== "auto" && model !== "router" && model !== "semantic")',
    '    return { selectedModel: model, taskType: "chat" as TaskType, autoRouted: false };',
    '  const taskType = classifyTask(messages || []);',
    '  return { selectedModel: MODEL_MAP[taskType], taskType, autoRouted: true };',
    '}',
    '',
    'function getAuthHeader() {',
    auth_header_line,
    '}',
    '',
    'const app = express();',
    'app.use(express.json({ limit: "50mb" }));',
    '',
    'app.get("/health", (_req, res) => {',
    '  res.json({ status: "ok", mode: "Semantic Router -> 9Router", taskTypes: Object.keys(MODEL_MAP) });',
    '});',
    '',
    'app.get("/v1/models", async (_req, res) => {',
    '  try {',
    '    const r = await axios.get(NINE_ROUTER_URL + "/models", { headers: getAuthHeader(), timeout: 10000 });',
    '    res.json(r.data);',
    '  } catch (e) {',
    '    res.json({',
    '      object: "list",',
    '      data: Object.entries(MODEL_MAP).map(([task, model]) => ({',
    '        id: model, object: "model", created: Date.now(), owned_by: "9router-master-combo",',
    '        description: "Task: " + task,',
    '      })),',
    '    });',
    '  }',
    '});',
    '',
    'app.post("/v1/chat/completions", async (req, res) => {',
    '  const start = Date.now();',
    '  const { selectedModel, taskType, autoRouted } = extractRequestInfo(req.body);',
    '  if (!selectedModel)',
    '    return res.status(400).json({ error: { message: "No model determined", type: "error" } });',
    '',
    '  const payload: any = {',
    '    model: selectedModel, messages: req.body.messages,',
    '    max_tokens: req.body.max_tokens || 4096,',
    '    temperature: req.body.temperature ?? 0.7,',
    '    stream: req.body.stream ?? false,',
    '  };',
    '  if (req.body.response_format) payload.response_format = req.body.response_format;',
    '  if (req.body.stop) payload.stop = req.body.stop;',
    '',
    '  try {',
    '    const response = await axios.post(NINE_ROUTER_URL + "/chat/completions", payload, {',
    '      headers: { ...getAuthHeader(), "Content-Type": "application/json" },',
    '      timeout: 120000,',
    '      responseType: req.body.stream ? "stream" : "json",',
    '    });',
    '    const elapsed = Date.now() - start;',
    '    if (req.body.stream) {',
    '      res.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" });',
    '      response.data.pipe(res);',
    '    } else {',
    '      res.json({ ...response.data, router_metadata: { task_type: taskType, model_selected: selectedModel, auto_routed: autoRouted, elapsed_ms: elapsed } });',
    '    }',
    '    console.log("[Proxy] OK " + selectedModel + " task=" + taskType + " " + elapsed + "ms");',
    '  } catch (error: any) {',
    '    const elapsed = Date.now() - start;',
    '    const status = error.response?.status || 502;',
    '    const msg = error.response?.data?.error?.message || error.message;',
    '    console.error("[Proxy] ERR " + selectedModel + " " + status + " " + (msg || "").slice(0, 100));',
    '    res.status(status).json({ error: { message: msg, type: "proxy_error" } });',
    '  }',
    '});',
    '',
    'app.listen(PORT, "0.0.0.0", () => {',
    '  console.log("Router Proxy running on port " + PORT);',
    '});',
    '',
]

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Written', len(lines), 'lines')
